[package]
name = "cashio-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.9.20"
solana-program = "1.9.20"
solana-program-test = "1.9.20"

anyhow = "1.0.57"
